### ISSUE TITLE
dense layer with no biases can't be converted

### ISSUE THREAD

**Issue by rurata** [scientific-computing/FKB#1]
Hi,
Thanks for your work with this repo. I have a tf.keras model saved as an .h5 file that I tried converting to text with convert_weights.py. However, it looks like the main Dense layers of my model don't have biases saved, and this makes the python script throw a "'bias:0' object doesn't exist" error.
I made a temporary workaround by just skipping adding the biases if they can't be found, but this leads to an end-of-file error when loading the model into Fortran. I'm guessing that the Fortran code is expecting to read the biases even if they aren't there. Any suggestions for solving this issue?

>> At line 208 of file /Users/rurata/work/FKB/src/lib/mod_network.F90
>> Fortran runtime error: End of file

**Comment by jordanott** [comment]
Thanks for raising this issue.  
This has been [resolved](https://github.com/scientific-computing/FKB/commit/e5b312eb61b044ea0a90482248587386c63383dc#diff-e52b98047aa934f16ac0a19c5c30146fR216-R223) by setting biases to zero if `use_bias = False`.
