### ISSUE TITLE
multi-input multi-output regression

### ISSUE THREAD

**Issue by lkampoli** [scientific-computing/FKB#10]
Hello,

thanks for this nice way to interface fortran and keras! 
I have a question about running a multi-input (or even single-input) and multi-output model. In this case, should I use an ensemble?

For example: 
input = temperature 
output = [concentration1, ..., concentration100]

What to do in this case? Also, I do need any average of the results when using ensembles. And also "Put the names of the model files" what does it mean? It assumes that my original network has been already splitted in many single outputs?

Thank you,
Kind regards,
Lorenzo Campoli

**Comment by jordanott** [comment]
Can you clarify what you mean by multi-output? This could mean two different things:
1. If you mean your output vector is of length 100, this will be taken care of by the conversion. 
2. Your output has multiple branches  

See [here](https://github.com/scientific-computing/FKB/tree/master/KerasWeightsProcessing#supported-models) for details on the difference and how FKB handles them

For ensembles first you must convert the keras files to Fortran format using `h5_to_txt`. Then you put the names of those txt files in a single file which is then provided to the ensemble. This way it knows which networks you want in the ensemble.

**Comment by lkampoli** [comment]
Hello, 
in my case is (1), the output vector has length 100. So, in this case ensembles are not necessary.

Thank you.
