### ISSUE TITLE
Should linear_prime return 1 instead of x?

### ISSUE THREAD

**Issue by milancurcic** [scientific-computing/FKB#3]
In [src/lib/mod_activation.F90](https://github.com/scientific-computing/FKB/blob/master/src/lib/mod_activation.F90), should `linear_prime` return 1 as the result rather than `x`?

```fortran
  pure function linear_prime(x, alpha) result(res)
    !! Linear activation function.
    real(rk), intent(in) :: x(:)
    real(rk), intent(in) :: alpha
    real(rk) :: res(size(x))
    res = x ! <-- should this be 1?
  end function linear_prime
```

It seems to me like it should.

Reported by septcolor [here](https://groups.google.com/d/msg/comp.lang.fortran/v7rl3QdqZQc/y3_L8VinAQAJ).

**Comment by jordanott** [comment]
Good catch! 
[Update](https://github.com/scientific-computing/FKB/commit/ee089eff24398400558ab83723261550f0eadf74)
