### ISSUE TITLE
Recognize InputLayer

### ISSUE THREAD

**Issue by mnijh** [scientific-computing/FKB#4]
Hi congratulation for the great work! 

A minor thing I realized during initial testing.
If the input layer of the model is given by 
```
model.add(keras.models.InputLayer(input_shape=5))
```
instead of 
```
model.add(Dense(8, input_dim=5, activation='relu'))
```
then this results in the error:
```
Traceback (most recent call last):
  File "convert_weights.py", line 353, in <module>
    h5_to_txt(
  File "convert_weights.py", line 183, in h5_to_txt
    info = model_config['config']['layers'][0]['config']['batch_input_shape'][1]
```

**Comment by jordanott** [comment]
Thanks for pointing this out. A number of people have run into this issue with the input layers. I'll see about incorporating it in.
