### ISSUE TITLE
Undefined TBP (train()) used in src/tests/example_simple.F90 and example_mnist.F90

### ISSUE THREAD

**Issue by septcolor** [scientific-computing/FKB#5]
src/tests/example_simple.F90 and example_mnist.F90 have this line:

```
call net % train(input, output, eta=xxx)   !! where xxx is some number
```
However, `% train()` is not defined for the `network_type` type, so the compilation fails.

The structure constructor for the `network_type` also fails because
the signature is different from that defined in mod_network.F90.
```
net = network_type([3, 5, 2])
```
So I am wondering these example files were possibly prepared for some former version of FKB, or possibly assuming neural-fortran...?

CC: @milancurcic (for possible relation with neural-fortran)

**Comment by jordanott** [comment]
Yes, these files were migrated over from neural-fortran but never properly integrated. I have now [removed](https://github.com/scientific-computing/FKB/commit/ff948722f5ae2cf2bba2ddb09f29ffba876c7dc8) them to avoid confusion.
