### ISSUE TITLE
Possible typo (filename) in the header comment of test_training.F90

### ISSUE THREAD

**Issue by septcolor** [scientific-computing/FKB#6]
src/tests/test_training.F90 has this header information:

```
! TO RUN
! ./test_training $NF_PATH/ExampleModels/simple_model_with_weights.txt

! load the simple_model
! train on simple example
!   run for 10 epochs
!   print predictions, targets, and loss
!   loss should decrease to verify backprop works
```
However, for some reason, using `ExampleModels/simple_model_with_weights.txt`  results in `End of file` error.

If I use `ExampleModels/simple_model.txt` instead, the test finishes successfully (with decreasing loss values).

**Comment by jordanott** [comment]
The `simple_model_with_weights.txt` was missing the learning rate value causing the EOF. The file has been [updated](https://github.com/scientific-computing/FKB/commit/bc25f5f36f796ac90b76b5352cba45372725261d#diff-35650a830aec85052c274f44276ba1b9R11).
