### ISSUE TITLE
"Unable to open object (object 'dense_1' doesn't exist)"

### ISSUE THREAD

**Issue by Maria1810** [scientific-computing/FKB#8]
I created a convolutional neural network in keras and when I run 

h5_to_txt(weights_file_name='model2.h5', output_file_name='model2.txt')

I get the following error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-34f56f9c292d> in <module>
----> 1 h5_to_txt(weights_file_name='model2.h5', output_file_name='model2.txt')

/media/nas/x21957/.../KerasWeightsProcessing/convert_weights.py in h5_to_txt(weights_file_name, output_file_name)
    211                 # get weights and biases out of dictionary
    212                 layer_weights = np.array(
--> 213                     model_weights[name][name]['kernel:0']
    214                 )
    215 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/media/nas/x21957/data/reinhardt/py3_venv/lib/python3.7/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    262                 raise ValueError("Invalid HDF5 object reference")
    263         else:
--> 264             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    265 
    266         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (object 'dense_1' doesn't exist)"

Can someone help?

**Comment by mnijh** [comment]
Did you give a name to the layers in keras? From my experience, h5_to_txt so far only works if you don't label the individual layers.

**Comment by Maria1810** [comment]
No, I did not label any layer.
I added them via 
model.add(Dense,...)
